image: docker

stages:
  - build
  - release

build:
  stage: build
  image: node:10
#  cache:
#    paths:
#      - node_modules/
  script:
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run build
  artifacts:
    paths:
      - dist

job-release:
  stage: release
  script:
    - docker info
    - DATE=`date +%Y%m%d`
    - TAG=$DATE-$CI_JOB_ID
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTER}
    - docker build -t ${DOCKER_REGISTER}/${PROJECT_NAME}:$TAG .
    - docker push ${DOCKER_REGISTER}/${PROJECT_NAME}:$TAG
    - docker tag ${DOCKER_REGISTER}/${PROJECT_NAME}:$TAG ${DOCKER_REGISTER}/${PROJECT_NAME}:latest
    - docker push ${DOCKER_REGISTER}/${PROJECT_NAME}:latest


